<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="OopExmplRandomObjectWithInterface" Id="{69daf245-9213-0e4a-2208-af7cea4de983}" SpecialFunc="None">
    <Declaration><![CDATA[(*This block implements interface "IOopExmpl" 
	>>this means is must have the methods described in the interface

*)
FUNCTION_BLOCK OopExmplRandomObjectWithInterface IMPLEMENTS IOopExmpl
VAR
	HM_b1:BOOL; //not used for example
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[//code we are not using in the interface example
HM_b1:=TRUE;
//...
//...
//...
//...
//...]]></ST>
    </Implementation>
    <Method Name="MustHaveMethod" Id="{55cbf681-63ec-0fb4-37b1-c79d8d7c158e}">
      <Declaration><![CDATA[//Method the object must implement because of the interface
METHOD MustHaveMethod : BOOL
VAR_INPUT
	I:BOOL;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[MustHaveMethod := I;]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>